version: 2

run:
  timeout: 10m

linters:
  default: none
  enable:
    - staticcheck
    - asciicheck
    - bidichk
    - bodyclose
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports
